### ISSUE TITLE
Check goto status?

### ISSUE THREAD

**Issue by GuillaumeGomez** [GuillaumeGomez/browser-UI-test#135]
In case of 404 for example...

**Comment by dns2utf8** [comment]
I assume not finding a file should fail the test immediately?

**Comment by GuillaumeGomez** [comment]
As you can see, for now I don't check anything: https://github.com/GuillaumeGomez/browser-UI-test/blob/292363dcefad36efbcacb676c4d79c37a88c1c72/src/commands.js#L477

Might be worth adding such a check and fail in case there is no such page.
