### ISSUE TITLE
Add an option to pause indefinitely on hitting an assertion failure

### ISSUE THREAD

**Issue by jsha** [GuillaumeGomez/browser-UI-test#242]
Related: https://github.com/rust-lang/rust/issues/92916

It would be useful to have a flag for debugging where the tool would keep the browser open indefinitely if it hits an assertion failure, so the user can debug what's going on. This would only make sense paired with --no-headless. Maybe it should automatically be turned on by --no-headless?

**Comment by GuillaumeGomez** [comment]
This is a very good idea! Implementing it.
