### ISSUE TITLE
Upgrade puppeteer dependency

### ISSUE THREAD

**Issue by jsha** [GuillaumeGomez/browser-UI-test#256]
Right now puppeteer is in package.json as 2.1.1, but it looks like upstream is up to 13.1.3: https://www.npmjs.com/package/puppeteer. We should upgrade! Among other things, I think puppeteer is shipping an old version of Chromium that doesn't render rustdoc pages correctly (with regards to hiding the default details disclosure element in particular).

**Comment by GuillaumeGomez** [comment]
Good catch! I didn't pay attention at all... Thanks!

**Comment by GuillaumeGomez** [comment]
I'll make a medium release because it could break some tests.
