### ISSUE TITLE
Emit all possible errors

### ISSUE THREAD

**Issue by jsha** [GuillaumeGomez/browser-UI-test#263]
Right now, browser-UI-test stops as soon as it hits an error. However, it should be possible to continue to evaluate any asserts, up until the next scripting command that changes the state of the page (goto, click, reload, etc).

**Comment by GuillaumeGomez** [comment]
It is possible but it would very noisy, which is why I didn't allow it. Do you want to be the default or do you want a command to enable this behaviour? Also, why stopping at page state changes?
